# Generated by Django 5.0.14 on 2026-07-08 17:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.ImageField(upload_to='products/thumbnails/')),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('preview_video', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('file', models.FileField(upload_to='products/files/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('license', models.CharField(choices=[('mit', 'MIT License'), ('gpl', 'GPL License'), ('apache', 'Apache 2.0'), ('commercial', 'Commercial'), ('personal', 'Personal Use'), ('other', 'Other')], default='mit', max_length=20)),
                ('documentation', models.URLField(blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_active'], name='products_pr_status_c4a457_idx'), models.Index(fields=['seller', 'status'], name='products_pr_seller__2449b8_idx'), models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'), models.Index(fields=['price', 'is_active'], name='products_pr_price_ce096c_idx')],
            },
        ),
    ]
