# Generated by Django 5.0.14 on 2026-07-13 07:55

import apps.profiles.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to=apps.profiles.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Zimbabwe', max_length=100),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='awarded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_badges', to=settings.AUTH_USER_MODEL),
        ),
    ]
