# Generated by Django 5.0.14 on 2026-07-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment_postedithistory_postlike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, null=True, unique=True),
        ),
    ]
